#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1525196129                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : https://drive.google.com/drive/folders/19NPq9lq0D7Hsew3i2vG8r5JZR5YffMxM?usp=sharing                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : An advanced differential equation solver.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Tanay Nistala                                
your_link                                 : https://tanaynistala.vercel.app                     
your_city                                 : Mumbai                                
email_address                             : nistalatanay@gmail.com
facebook_username                         :                                           
instagram_username                        : tanaynistala
twitter_username                          : timswagwalker
github_username                           : tanaynistala
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Configurable
    description                           : Easily set the order, angle unit, and precision of your differential equation.
    fontawesome_icon_name                 : cog

  - title                                 : Presets
    description                           : We've put in some of the most commonly-used differential equations, so you don't have to.
    fontawesome_icon_name                 : layer-group

  - title                                 : Expressions
    description                           : Enter mathematical expressions and have them evaluated with the equation. No separate calculator needed.
    fontawesome_icon_name                 : calculator

  - title                                 : Dark Mode
    description                           : A beautiful dark mode is easy on your eyes at night.
    fontawesome_icon_name                 : moon
  
  - title                                 : Custom Math Keyboard
    description                           : The custom keyboard lets you quickly enter common mathematical operators and constants.
    fontawesome_icon_name                 : keyboard

  - title                                 : On-Device
    description                           : All processing is done locally on-device, so you don't need an internet connection to use the app.
    fontawesome_icon_name                 : tablet-alt

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#5856D6"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#5856D6"
feature_icons_background_color            : "#CDCCF3"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
